Make input-columns configurable
dataware-tools/app-data-browser-next pull request #173
Opened 2021-10-14 05:49 UTC by d-hayashi

## What?
- Make existing input-columns editable with on a modal
- Add settings of visibility on the modal

## Why?
To improve usability

## Screenshot or video [Optional]
### Before
<img width="659" alt="スクリーンショット 2021-10-14 14 37 31" src="https://user-images.githubusercontent.com/24401842/137259286-3eaf27b2-c07f-460d-8b8f-8f2758258c39.png">
<img width="616" alt="スクリーンショット 2021-10-14 14 37 48" src="https://user-images.githubusercontent.com/24401842/137259308-df894610-8180-4d95-868a-dd5a55a1f38d.png">

### After
<img width="526" alt="スクリーンショット 2021-10-14 14 38 09" src="https://user-images.githubusercontent.com/24401842/137259317-579cda9d-6122-43a4-b501-e566df9c9119.png">
<img width="614" alt="スクリーンショット 2021-10-14 14 38 16" src="https://user-images.githubusercontent.com/24401842/137259320-e9987c08-6293-4c01-8ab9-055faef02935.png">

2021-10-14 05:49 UTC, hdl-service commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/173#" title="Author self-approved">d-hayashi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-10-14 09:18 UTC, WatanabeToshimitsu requested changes
あざます
めっちゃ使いやすくなってると思います！！

例の如く細かいとこ指摘させてもらいました

2021-10-18 08:36 UTC, WatanabeToshimitsu commented on src/components/organisms/InputConfigList.tsx
> -                  order_of_input: order.length,
試してみたら，確かに更新される奴まで動いちゃってたので，これは無視してください

2021-10-19 03:10 UTC, d-hayashi commented on src/components/molecules/InputConfigListItem.tsx
> +        <IconButton onClick={() => onConfigure()}>
ご指摘あざます！
修正しておきます

2021-10-19 06:23 UTC, merged