Fix the feature of downloading metadata
dataware-tools/app-data-browser-next pull request #372
Opened 2022-01-25 03:39 UTC by d-hayashi

## What?
メタ情報のエクスポート機能で以下の点を修正:
- csvでの出力時に無駄に `"` で囲われる問題を修正
- カラム名が display_name に変換されていなかった問題を修正
- ファイルパスに `/` など不要なものが含まれていた問題を修正

## Why?
バグ修正のため

2022-01-25 03:39 UTC, hdl-service commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/372#" title="Author self-approved">d-hayashi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-25 06:55 UTC, WatanabeToshimitsu requested changes
例の如く細かいとこをいくつか
let 撲滅とか、宗教的なとこは無視してもらって全然大丈夫です

2022-01-25 06:55 UTC, WatanabeToshimitsu commented on src/components/organisms/ExportMetadataModal.tsx
> +          if (value instanceof Array) {
Array の判定には instanceof よりも Array.isArray を使うことが基本推奨されてます
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray

2022-01-25 06:55 UTC, WatanabeToshimitsu commented on src/components/organisms/ExportMetadataModal.tsx
> +          if (value instanceof Object || value instanceof Array) {
ここでは問題にならないと思うんですが、Javascript で「その変数が (python で言うとこの）辞書型かどうか」を判定するのは結構面倒なので、Tips 的な感じで記します

[少なくとも instanceof を使うと Date や String、Array に対しても true を返すので、正確には辞書型であるか判別できません](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/instanceof#demonstrating_that_string_and_date_are_of_type_object_and_exceptional_cases)

調べてみると、`typeof === "object"` かつ  `!== null` を使うのが望ましいようです詳しくは
↓を参考にしていただければと....
https://chaika.hatenablog.com/entry/2019/08/16/083000
https://zenn.dev/suin/books/8985cbff87b524e11c2b/viewer/01e63d
ってあんまりしっかりとした

あと、上述したように配列の判定には Array.isArray が推奨されてます

2022-01-25 06:55 UTC, WatanabeToshimitsu commented on src/components/organisms/ExportMetadataModal.tsx
> +        let newValue = value;
let に恨みがあるわけじゃないんですが
```
const newValue = (key === "path" && Array.isArray(value)) ? value.filter(~~~) : value
```
とすると let を撲滅できる気がするので報告まで...

2022-01-25 07:41 UTC, d-hayashi commented on src/components/organisms/ExportMetadataModal.tsx
> +          if (value instanceof Object || value instanceof Array) {
なるほど。。`instanceof` ってそういう仕様だったんですね。修正します！

2022-01-25 07:41 UTC, d-hayashi commented on src/components/organisms/ExportMetadataModal.tsx
> +          if (value instanceof Array) {
指摘あざます！修正します

2022-01-25 07:44 UTC, d-hayashi commented on src/components/organisms/ExportMetadataModal.tsx
> +        let newValue = value;
んー、let, var をあまり使いたくない気持ちも分からなくないですが、個人的には可読性と拡張性を考えると `let` を使った実装の方が好みです。。

2022-01-25 08:07 UTC, d-hayashi commented on src/components/organisms/ExportMetadataModal.tsx
> +          if (value instanceof Object || value instanceof Array) {
よくよく考えたら Date 型とかも JSON 文字列に変換する必要があるので `value instanceof Object` の部分はそのまま使おうかと思ったのですが、どう思います？

2022-01-26 05:55 UTC, WatanabeToshimitsu commented on src/components/organisms/ExportMetadataModal.tsx
> +        let newValue = value;
完全に宗教の話をしたので大丈夫です！

2022-01-26 05:56 UTC, WatanabeToshimitsu commented on src/components/organisms/ExportMetadataModal.tsx
> +          if (value instanceof Object || value instanceof Array) {
確かに...
このままでいきましょう！

2022-01-26 05:56 UTC, WatanabeToshimitsu approved these changes
LGTM!

2022-01-26 05:56 UTC, hdl-service commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/372#" title="Author self-approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/372#pullrequestreview-863134116" title="Approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-26 05:57 UTC, merged