Use toast for visualizing error on database add and update
dataware-tools/app-data-browser-next pull request #483
Opened 2022-07-28 07:40 UTC by yusukefs

## What?

- app-commonのToasterコンポーネントとToastHavingDetailInfoコンポーネントをエラーのフィードバックとして使うようにした
- ひとまずデータベース追加・更新時に対応

## Why?

ある操作に対する一時的なエラーをトーストに切り替えたい

## See also [Optional]

PR on app-common: https://github.com/dataware-tools/app-common/pull/258

## Screenshot or video [Optional]

https://user-images.githubusercontent.com/13210107/181449193-1e40829f-1227-46b6-8b76-a3bcd829863c.mov

2022-07-28 07:42 UTC, yusukefs commented
@WatanabeToshimitsu 
ひとまず例としてデータベース追加・更新時のみトーストに対応してみました。
トーストを使うたびにToasterコンポーネントを入れるのは面倒なのでApp.tsxに入れたのを懸念しているのですが何か問題は考えられるでしょうか？

2022-07-28 07:44 UTC, yusukefs commented
あと動作確認していたら気づいたのですが、現状同じ名前のデータベースを作成しようとするとはじめはエラーになりますが、その際にそのデータベースを削除するリクエストが飛び、もう一度サブミットすると作成できてしまうという挙動になっていました。
これはおそらく意図したものではないですよね？

2022-07-28 07:46 UTC, yusukefs commented
enqueueErrorToastForFetchError関数については、app-user-managerでも使えそうならapp-commonに移動するのもありそうです

2022-07-28 08:13 UTC, WatanabeToshimitsu commented
> あと動作確認していたら気づいたのですが、現状同じ名前のデータベースを作成しようとするとはじめはエラーになりますが、その際にそのデータベースを削除するリクエストが飛び、もう一度サブミットすると作成できてしまうという挙動になっていました。 これはおそらく意図したものではないですよね？

滅茶苦茶やばいバグやんけ.... と思ったらすぐにわかるレベルでそういうコードになってました　こちらは僕の方で対応します！　発見あざます！

2022-07-28 08:50 UTC, WatanabeToshimitsu commented
> @WatanabeToshimitsu ひとまず例としてデータベース追加・更新時のみトーストに対応してみました。 トーストを使うたびにToasterコンポーネントを入れるのは面倒なのでApp.tsxに入れたのを懸念しているのですが何か問題は考えられるでしょうか？ もし問題なければ他の箇所も別PR（？）で対応していこうと思います。

Toaster自体は、react-toastify の TostContainer コンポーネントのラッパーでしかないので、正確なことは全然分からないんですが、特に問題が思い浮かびません
「毎回 ToastContainer を呼び出すようなライブラリが流行るはずがないから大丈夫やろ」くらいの感じです

2022-07-28 09:03 UTC, WatanabeToshimitsu requested changes
今回の変更で、 error ステートの管理が不要になっているはずなので、そこの削除もお願いしたいです！

2022-07-28 09:03 UTC, WatanabeToshimitsu commented on src/components/organisms/DatabaseEditModal.tsx
> -      setError({ reason, instruction });
コードが悪い噛み合い方をして linter や tsc がエラーを吐いてないんですが、この辺のコードの削除のおかげで error ステートの管理が不要になっているはずです

2022-07-29 01:29 UTC, yusukefs commented on src/components/organisms/DatabaseEditModal.tsx
> -      setError({ reason, instruction });
errorステート周りの不要になった部分削除しました！

2022-07-29 01:57 UTC, yusukefs commented
> app-common に色々入れすぎた反省を活かして、実際に user-manager に入れる時にそうして、data-browser はその後の任意のタイミングで app-common から使うようにしたいと思っています　どうでしょう？

そうですね！一旦data-browserは今のまま一通りトーストの実装を続けて、次user-managerで実装するときに同じ実装になったらapp-commonに入れる流れがよさそうですね。

2022-07-29 08:09 UTC, WatanabeToshimitsu approved these changes
LGTM!

2022-07-29 08:09 UTC, merged