[WIP] Improve breadcrumbs
dataware-tools/app-data-browser-next pull request #81
Opened 2021-07-15 06:09 UTC by yusukefs

## What?

- パンくずリストをわかりやすくした
- 別のコンポーネントに切り分けた

## Why?

- 現在のページ名がわかると良い
- 一般的なパンくずリストにする

## TODOs

- [x] コンポーネント作成
- [ ] Story作成

## See also [Optional]

Issue: https://github.com/dataware-tools/dataware-tools/issues/10

## Screenshot or video [Optional]

### データベース一覧ページ

<img width="900" alt="スクリーンショット 2021-07-15 15 04 13" src="https://user-images.githubusercontent.com/13210107/125737230-d4e6feeb-775e-4638-8258-ea249a2c6392.png">

### データベースシングルページ

<img width="893" alt="スクリーンショット 2021-07-15 15 04 17" src="https://user-images.githubusercontent.com/13210107/125737242-770791aa-9cc2-4f1a-bb10-796067c23784.png">

2021-07-15 06:09 UTC, hdl-service commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/81#" title="Author self-approved">yusukefs</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [yusukefs]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-15 06:11 UTC, yusukefs commented
もしかしたら app-common に入れたほうが良いかも

2021-07-15 08:33 UTC, WatanabeToshimitsu requested changes
あざます！見た目も機能も完璧です！
バンドルサイズに関わる部分や，書き方についていくつか指摘させてもらいました！

2021-07-15 08:33 UTC, WatanabeToshimitsu commented on src/components/molecules/Breadcrumbs.tsx
> +import * as MuiIcons from "@material-ui/icons";
ここの import をなくしてみたら，バンドルサイズが 1M くらい減りました
親コンポーネントから icon を渡す形にできますか...？

2021-07-15 08:33 UTC, WatanabeToshimitsu commented on src/components/molecules/Breadcrumbs.tsx
> +  const breadcrumbItems: JSX.Element[] = items.map(
この書き方って何かを参考にされましたか？
特段問題になる書き方ではないと思うんですが，個人的にあまり見かけないので....

（めちゃくちゃ細かいことを気にするなら，もしこの `breadcrumbItems` がレンダリングされないような場合でも，計算だけされちゃってちょっと計算コストがかさむ，みたいなのはあります）

2021-07-15 08:33 UTC, WatanabeToshimitsu commented on src/components/molecules/Breadcrumbs.tsx
> +import React from "react";
出来れば，1 ファイルの中に記述するのは，1 コンポーネントの ビュー部分 + ロジック部分 ＋ 型 + 関数  だけになってると嬉しいです
他のコンポーネントはある程度一貫性を保った記述をしてるつもりなので，よければ一度参考に見てもらえればと...

2021-07-15 08:33 UTC, WatanabeToshimitsu commented on src/components/molecules/Breadcrumbs.tsx
> +import React from "react";
かなり一人よがりな記述方法になってておかしくないので，もし見てみた中で「これ違う」とか「この書き方はちょっと...」みたいなのがあれば遠慮なく言ってください！

2021-07-15 09:50 UTC, yusukefs commented
@WatanabeToshimitsu 
コメントあざます！
修正します

2021-07-15 10:18 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +  const breadcrumbItems: JSX.Element[] = items.map(
（Reactの理解がまだ浅いのであれなんですが）関数コンポーネントはレンダリング毎に呼ばれていて、return内に書いても外に書いても呼ばれる回数（計算コスト？）は同じという理解だったので、単にコードの見やすさのためにこう書いてました
なにか参考になる記事などあれば是非おしえてください！

レンダリング毎に関数が呼ばれるというのは↓を参考にしてまして、公式のリファレンスは見つけられてないです・・
https://overreacted.io/ja/a-complete-guide-to-useeffect/#:~:text=render%20%E6%AF%8E%E3%81%AB%E4%B8%80%E5%BA%A6

2021-07-15 10:21 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +  const breadcrumbItems: JSX.Element[] = items.map(
useMemoでコストを軽減できる気もするのでちょっと試してみます

2021-07-15 10:22 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +import * as MuiIcons from "@material-ui/icons";
たしかにアイコン全部バンドルする形になるのでよくないですね・・
使われているやつだけバンドルできたら最高ですが、何も思いつかないので親から渡す形にします！

2021-07-16 00:56 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +  const breadcrumbItems: JSX.Element[] = items.map(
リファレンスに2パターンで書かれているものがありましたが、特に違いは明記されていなかったので書き方以外に違いが無いのかもしれません
https://ja.reactjs.org/docs/lists-and-keys.html

2021-07-16 01:17 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +import React from "react";
BreadcrumbsItem は Breadcrumbs でしか使わないだろうと思って同じファイルに入れていたんですが、atomic designだとそういうのも atoms に入れたほうが良いでしょうか？
それか Breadcrumbs コンポーネントをディレクトリにしてその中に入れるのもありですかね

2021-07-16 02:51 UTC, WatanabeToshimitsu commented on src/components/molecules/Breadcrumbs.tsx
> +  const breadcrumbItems: JSX.Element[] = items.map(
あ，いや，特に深い意味はなくて，本当に「ただあまり見たことがないな」と思っただけで...
リファレンスに書いてある書き方なので多分問題ないんだと思います！

一応，僕が気にしてるのは
```
return someParam ? listItem : null
```
というコードであった場合です
someParam が falsy になるなら
```
return someParam ? items.map(~~~~) : null
```
の方が最適化出来ているのかなと...
少し調べてもそういった記述がないので，確証はないんですが....

2021-07-16 03:22 UTC, WatanabeToshimitsu commented on src/components/molecules/Breadcrumbs.tsx
> +import React from "react";
うーーーーーーーーーーーーーーーーーーーーーーーーーーん
今まではとりあえず脳死で atoms に入れる形にしていたんですが，今の気持ちとしてはディレクトリを作る方が妥当な気がしています
というのも
- 「デザイン上の粒度で分ける atomic design の分け方を，そのままコードの分割として採用するのどうなの」みたいな話を割と聞く
- molecules に入れるか organisms に入れるかを迷って，時間を浪費しがち
- コンポーネントをディレクトリから探すときに「どこに入れたっけ...？」みたいなのもあるある
- 汎用性が高い atoms や molecules は app-common に移りがちで，organisms だけが肥大化していく
みたいな感じで，atomic design の粒度に分けて管理する利点よりも，欠点の方が最近は目立ってきていて....
Material-UI レベルの，巨大なコンポーネントライブラリでも特にディレクトリを分けてないことが確認できたのも個人的には大きいです

とは言いつつも，確信になってるほどじゃないので，判断はお任せします

2021-07-16 04:00 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +  const breadcrumbItems: JSX.Element[] = items.map(
たしかに！そういうケースだと検証は必要ですが後者のほうが減りそうに見えますね
まあでも今回の場合だとどちらも変わらなさそうなのでとりあえずこのまま行こうかなと思います！

2021-07-16 04:07 UTC, yusukefs commented on src/components/molecules/Breadcrumbs.tsx
> +import React from "react";
たしかに app-common があるのでだいぶ事情が異なっていてややこしいですよね
とりあえずディレクトリ作る方向で実装してみます！

2021-07-16 04:39 UTC, yusukefs commented
@WatanabeToshimitsu 
コンポーネント用のフォルダを作成して、1コンポーネント1ファイルになるように修正しましたがどうでしょうか？

2021-07-16 05:03 UTC, WatanabeToshimitsu approved these changes
あざます！！LGTM！

2021-07-16 05:03 UTC, hdl-service commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/81#pullrequestreview-708009289" title="Approved">WatanabeToshimitsu</a>*, *<a href="https://github.com/dataware-tools/app-data-browser-next/pull/81#" title="Author self-approved">yusukefs</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-data-browser-next).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-data-browser-next/blob/master/OWNERS)~~ [WatanabeToshimitsu,yusukefs]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-16 05:04 UTC, merged